### ISSUE TITLE
Estimate normals for own data

### ISSUE THREAD

**Issue by larissamumme** [ActiveVisionLab/NINormal#2]
I'd like to use a pretrained model on a specific point cloud (not in the test data) for estimating the normals. I'm not sure how to do this as I'm new to this and the README only explains how to achieve the results presented in the paper with the test data.

So far, I've tried to substitute the test data with my own so I created an h5 file with the preprocessing script. Running the test.py script on that data with one of the pretrained models returns a KeyError: "Unable to open object (object '0000000044' doesn't exist)". I really don't know what's wrong here or if I'm on the right track. On the internet, I've found that maybe something is wrong with the h5 file. Do you have any tips for me? Maybe there's a way to use the pretrained model without a h5 file since I only want to process one point cloud.

**Comment by ziruiw-dev** [comment]
Hi @larissamumme,

It sounds like you need to change the number hardcoded [here](https://github.com/ActiveVisionLab/NINormal/blob/8eb1d71cc248be42d86bcedb24bfaceb74b12864/PcpKnnPatchesDataset.py#L53) to the final `global_patch_counter` [here](https://github.com/ActiveVisionLab/NINormal/blob/8eb1d71cc248be42d86bcedb24bfaceb74b12864/utils/preprocess_pcp_knn_patches.py#L103)  (just print it at the end of preprocessing). The dataloader I provided was specifically designed for the PCP dataset, in which each shape contains exactly 100k points and 4 noise levels. For your own data, you probably need to write your own dataloader.

Also, since the pretrained network was trained only on PCPNet data, I doubt it can work very well on other datasets straightaway because these datasets might have different properties than PCPNet. For example, point cloud density difference, maybe the point cloud is acquired from a lidar, or a depth sensor, whether it is a partial scan or a complete object, etc. So you probably need to train from scratch with your data.

Best,
Zirui

**Comment by larissamumme** [comment]
I see. Thank you for the explanation and the advice! :)
